# ==========================================
# ZENIT - Prometheus Configuration
# ==========================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'zenit-monitor'
    environment: 'production'

# Alertmanager configuration (opcional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Regras de alerta
rule_files:
  # - "alerts/*.yml"

# Configuração de scrape
scrape_configs:
  # ==========================================
  # Backend API Metrics
  # ==========================================
  - job_name: 'zenit-backend'
    static_configs:
      - targets: ['backend:3001']
        labels:
          service: 'api'
          component: 'backend'
    
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # ==========================================
  # Redis Metrics
  # ==========================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'cache'
          component: 'redis'

  # ==========================================
  # Prometheus Self-Monitoring
  # ==========================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'monitoring'
          component: 'prometheus'

  # ==========================================
  # Node Exporter (se configurado)
  # ==========================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'
          component: 'node-exporter'
